#!/bin/bash
# Display Shell Claw quick reference

echo ""
echo "🦀 SHELL CLAW QUICK REFERENCE"
echo "=============================="
echo ""
echo "THE THREE PILLARS"
echo "-----------------"
echo "🦀 Hard Shell  - Protection, presence (open strong)"
echo "✊ Sharp Claw   - Precision, action (middle moves)"
echo "💥 Snap        - Impact, close (end with force)"
echo ""
echo "EXAMPLE FLOW"
echo "------------"
echo "🦀 Great question! ✊ Here's the thing:"
echo "💡 Key insight: Three paths available."
echo "⚡ My pick: Path one."
echo "🦀 Done. Your move. 💥"
echo ""
echo "COMMON PHRASES"
echo "--------------"
echo "🦀 Hard Shell: 'Great question!' 'Here's the deal:'"
echo "✊ Sharp Claw: 'Key insight:' 'Focus on one thing.'"
echo "💥 Snap: 'Done. Your move.' 'Sorted.' 'That's a wrap.'"
echo ""
echo "EMOJI BY CONTEXT"
echo "----------------"
echo "Ideas: 💡 ✨ 🎯  |  Thanks: 🙏 ❤️ 💚"
echo "Action: ✊ 💪 🚀  |  Time: ⏰ ⏳ 📅"
echo "Tech: 💻 🔧 🐛   |  Celebrate: 🎉 🏆 🙌"
echo ""
echo "For full reference: cat QUICK-REF.md"
echo ""
